version: 1.0.{build}
skip_branch_with_pr: true
image: Visual Studio 2017
configuration: Release
environment:
  matrix:
  - BUILD_PLATFORM: x64
    VS_GENERATOR: Visual Studio 15 2017 Win64
  - USE_SDL2: 1
    BUILD_PLATFORM: x64
    VS_GENERATOR: Visual Studio 15 2017 Win64
install:
- cmd: >-

    IF not exist "build_%BUILD_PLATFORM%" mkdir "build_%BUILD_PLATFORM%"

    cd "build_%BUILD_PLATFORM%"

    cmake -G "%VS_GENERATOR%" -T "%VS_TOOLSET%" ..\source\ -DUSE_SDL2=%USE_SDL2%

    cd ..
build_script:
- cmd: >-
    msbuild build_%BUILD_PLATFORM%\qfusion.sln /p:configuration=Release /maxcpucount:2

    IF "%USE_SDL2%"=="1" cp libsrcs/lib/win32/%BUILD_PLATFORM%/release/SDL2.dll source\build\Release

    cd source\build\Release

    >>commit.txt echo %APPVEYOR_REPO_COMMIT%

    IF "%USE_SDL2%"=="1" 7z a ..\..\..\win_%BUILD_PLATFORM%-SDL-Release.zip * -r -x!*.exp -x!*.lib

    IF "%USE_SDL2%"=="" 7z a ..\..\..\win_%BUILD_PLATFORM%-Release.zip * -r -x!*.exp -x!*.lib

    cd ..\..\..\
