sudo: false
language: c++
install: true
cache: apt

matrix:
  include:
    - os: linux
      env: QF_ARCH=x86_64
      addons:
        apt:
          packages:
            - build-essential
            - libopenal-dev
            - libjpeg-dev
            - libvorbis-dev
            - libtheora-dev
            - libfreetype6-dev
            - libsdl2-dev
            - zlib1g-dev
            - libcurl4-gnutls-dev
    - os: linux
      env: QF_ARCH=win32_x86
      addons:
        apt:
          sources:
            - kubuntu-backports
          packages:
            - cmake
            - binutils-mingw-w64-i686
            - binutils-mingw-w64-x86-64
            - gcc-mingw-w64-i686
            - gcc-mingw-w64-x86-64
            - gcc-mingw-w64
            - g++-mingw-w64-i686
            - g++-mingw-w64-x86-64
            - g++-mingw-w64
            - mingw-w64
    - os: linux
      env: QF_ARCH=win32_x86_64
      addons:
        apt:
          sources:
            - kubuntu-backports
          packages:
            - cmake
            - binutils-mingw-w64-i686
            - binutils-mingw-w64-x86-64
            - gcc-mingw-w64-i686
            - gcc-mingw-w64-x86-64
            - gcc-mingw-w64
            - g++-mingw-w64-i686
            - g++-mingw-w64-x86-64
            - g++-mingw-w64
            - mingw-w64

before_install:
  - if [[ "$QF_ARCH" == "win32_x86" ]]; then cd source && cmake -DCMAKE_TOOLCHAIN_FILE=cmake/i686-mingw.cmake -DCMAKE_C_FLAGS=-m32 -DCMAKE_CXX_FLAGS=-m32; fi
  - if [[ "$QF_ARCH" == "win32_x86_64" ]]; then cd source && cmake -DCMAKE_TOOLCHAIN_FILE=cmake/x86_64-mingw.cmake; fi

install:
  - if [[ "$QF_ARCH" == "x86_64" ]]; then curl -O http://www.libsdl.org/release/SDL2-2.0.4.tar.gz && tar -xzvf SDL2-2.0.4.tar.gz && cd SDL2-2.0.4 && ./configure --prefix="$HOME/.deps/sdl2" && make && make install && cd ../source && cmake; fi

script:
  - make -j2

