sudo: false
dist: xenial
cache: 
  apt: true
  directories:
    - $HOME/.deps
notifications:
  email: false

matrix:
  include:
    - os: osx
      osx_image: xcode10.3
      env: QF_ARCH=OSX
      language: c++
      compiler: clang
    - os: linux
      language: c++
      compiler: clang
      env: QF_ARCH=x86_64
      addons:
        apt:
          update: true
          packages:
            - clang
            - cmake
            - build-essential
            - libsdl2-dev
            - libvorbis-dev
            - libtheora-dev	
            - libfreetype6-dev
            - zlib1g-dev

install:
  - if [[ "$QF_ARCH" == "x86_64" ]]; then export CC=clang CXX=clang++; fi
  - cd "$TRAVIS_BUILD_DIR/source"
  - if [[ "$QF_ARCH" == "x86_64" ]]; then cmake .; fi
  - if [[ "$QF_ARCH" == "OSX" ]]; then cmake -G Xcode .; fi

script:
  - cd source
  - if [[ "$QF_ARCH" == "x86_64" ]]; then make -j8; fi
  - if [[ "$QF_ARCH" == "OSX" ]]; then xcodebuild -project qfusion.xcodeproj/ -jobs 4 -configuration Release -scheme ALL_BUILD | xcpretty; fi
